### ISSUE TITLE
[rancher-logging] rancher-logging-rke does not properly handle time

### ISSUE THREAD

**Issue by ebauman** [rancher/charts#915]
In `configmaps/rancher-logging-rke`, the INPUT section specifies a parser of `json` by default:
```
    [INPUT]
        Tag               rke
        Name              tail
        Path_Key          filename
        Parser            json
```

This parser does not properly handle time as output by Docker. This is evidenced in error messages such as:

```
│ [2020/12/23 16:42:09] [error] [parser] cannot parse '2020-12-23T16:42:09.768627233Z'                                                                                                                         │
│ [2020/12/23 16:42:09] [ warn] [parser:json] invalid time format %d/%b/%Y:%H:%M:%S %z for '2020-12-23T16:42:09.768627233Z'
```

By changing the Parser to docker, times are properly handled. 

gz#15583

**Comment by ebauman** [comment]
Specifically, change https://github.com/rancher/charts/blob/d4f61a2bea7a94cd83c37c3e2c07c813fd2bc553/charts/rancher-logging/templates/loggings/rke/configmap.yaml#L18

**Comment by axeal** [comment]
Also encountered this with rancher-logging 3.9.000, a fix for this appears to be in dev-v2.5 (https://github.com/rancher/charts/commit/e88c1162680d70c9321427d6f45f08a2401d8645#diff-a775af99fca44ea78e1e33b81a3187c0f4c3c36a2c3af10725519cb6f427e083) and in the latest RCs (https://github.com/rancher/charts/blob/dev-v2.5/charts/rancher-logging/rancher-logging/3.9.400-rc03/templates/loggings/rke/configmap.yaml).

FTR, in my testing of 3.6.001 and 3.8.201 this error was not seen, due to a separate error loading the json parser (which was fixed in 3.9.000):

```
[2021/04/15 09:12:50] [Warning] [config] I cannot open /fluent-bit/etc/..2021_04_15_09_12_42.230513976/parsers.conf file
Fluent Bit v1.5.4
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
[2021/04/15 09:12:50] [ info] [engine] started (pid=1)
[2021/04/15 09:12:50] [ info] [storage] version=1.0.5, initializing...
[2021/04/15 09:12:50] [ info] [storage] in-memory
[2021/04/15 09:12:50] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/04/15 09:12:50] [error] [input:tail:tail.0] parser 'json' is not registered
[2021/04/15 09:12:50] [error] [sqldb] cannot open database /tail-db/tail-containers-state.db
[2021/04/15 09:12:50] [error] [input:tail:tail.0] could not open/create database
[2021/04/15 09:12:50] [ info] [sp] stream processor started
```

**Comment by izaac** [comment]
This is reproducible by installing the chart with `additionalLoggingSources.rke.enabled = true` and chart version `3.9.000`
Then check the logs in the pods members of the `rancher-logging-rke-aggregator` Daemonset.

```
[2021/05/04 18:41:26] [ warn] [parser:json] invalid time format %d/%b/%Y:%H:%M:%S %z for '2021-05-04T18:41:26.786724437Z'

[2021/05/04 18:41:36] [error] [parser] cannot parse '2021-05-04T18:41:36.841730409Z'

[2021/05/04 18:41:36] [ warn] [parser:json] invalid time format %d/%b/%Y:%H:%M:%S %z for '2021-05-04T18:41:36.841730409Z'

[2021/05/04 18:41:46] [error] [parser] cannot parse '2021-05-04T18:41:46.905719025Z'

[2021/05/04 18:41:46] [ warn] [parser:json] invalid time format %d/%b/%Y:%H:%M:%S %z for '2021-05-04T18:41:46.905719025Z'
```

`rancher-logging-rke` Configmap excerpt:

```
[INPUT]
    Tag               rke
    Name              tail
    Path_Key          filename
    Parser            json
    DB                /tail-db/tail-containers-state.db
    Mem_Buf_Limit     5MB
    Path              /var/lib/rancher/rke/log/*.log
```


In  `3.9.4000` the parser errors aren't seen in the pod logs.

and the `rancher-logging-rke` Configmap Parser is now `docker` in the INPUT section:

```
[INPUT]
    Tag               rke
    Name              tail
    Path_Key          filename
    Parser            docker
    DB                /tail-db/tail-containers-state.db
    Mem_Buf_Limit     5MB
    Path              /var/lib/rancher/rke/log/*.log
```

Rancher version `v2.5.8-rc18`

**Comment by devildev2018** [comment]
HI Team,

Still not able to parse the logs from /var/lib/rancher/rke/log

Tried using both docker and json as parser. 

Not working in both 3.9.4000 and 3.15

Kindly advise.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/42323067/157613713-7d721a89-2202-4e6e-80d8-8033c34e25f1.png">
